---
- defaults:
    link:
      relink: true
    shell: 
      stdout: true
      stderr: true


- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.ideavimrc: ideavimrc
    ~/.fzf: fzf/
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.zshenv: zshenv
    ~/.zprezto: zprezto
    ~/.zpreztorc: zpreztorc
    ~/.bash_profile: bash_profile
    ~/.functions: functions
    ~/.aliases: aliases
    ~/.config: config
    ~/.config/wezterm: wezterm/
    ~/.config/nvim: vim/
    ~/.config/sketchybar: sketchybar
    ~/.config/aerospace: aerospace
    ~/.config/aerospace-swipe: aerospace-swipe
    ~/.config/nvim/init.vim: vimrc
    ~/Library/Application Support/Cursor/user/settings.json: cursor/settings.json
    ~/Library/Application Support/Cursor/user/keybindings.json: cursor/keybindings.json
    ~/.ycm_extra_conf.py: vim/settings/ycm_extra_conf.py
    ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/base16_kaye.vim: vim/lightline/base16_kaye.vim
    ~/.zprezto/modules/prompt/functions/prompt_kaye_setup: zsh/prompt_kaye_setup
    ~/.local/state/crossnote/style.less: cursor/markdown-styles/style.less

- shell:
    -
      - "bash brew.sh"
      - "Installing Homebrew packages and applications"
    -
      - "tempfile=$(mktemp) \
        && curl -o $tempfile https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo \
        && tic -x -o ~/.terminfo $tempfile \
        && rm $tempfile"
      - "Installing WezTerm terminfo"
    -
      - "ln -sf $(brew --prefix)/share/git-core/contrib/diff-highlight/diff-highlight /usr/local/bin/diff-highlight"
      - "Installing improved diff highlighting"
    -
      - "git submodule update --init --recursive --remote"
      - "Installing/updating submodules"
    -
      - "mkdir -p ~/.vim/autoload ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme"
      - "Checking folder structure exists"
    -
      - "mkdir ~/.vim/undodir"
      - "Checking folder structure exists"
    -
      - "mkdir -p ~/.local/state/crossnote"
      - "Creating markdown stylesheet directory"
    -
      - "gem install tmuxinator"
      - "Installing tmuxinator"
    -
       - "bash cursor/manage-extensions.sh install" 
       - "Installing Cursor extensions"
    -
       - "mkdir -p /tmp/aerospace-swipe-install && cd /tmp/aerospace-swipe-install && \
          git clone https://github.com/acsandmann/aerospace-swipe.git && \
          cd aerospace-swipe && \
          make install && \
          z dotfiles && \
          rm -rf /tmp/aerospace-swipe-install"
       - "Installing aerospace-swipe for trackpad gesture support"

