---
- defaults:
    link:
      relink: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux/
    ~/.gitmux.conf: tmux/gitmux.conf
    ~/.ideavimrc: ideavimrc
    ~/.bat.conf: zsh/bat.conf
    ~/.zsh_plugins.txt: zsh/zsh_plugins.txt
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.zshenv: zshenv
    ~/.bash_profile: bash_profile
    ~/.functions: functions
    ~/.aliases: aliases
    ~/.config: config
    ~/.config/wezterm: wezterm/
    ~/.config/nvim: nvim/
    ~/.config/sketchybar: sketchybar
    ~/.config/aerospace: aerospace
    ~/.config/starship.toml: zsh/starship.toml
    ~/Library/Application Support/Cursor/user/settings.json: cursor/settings.json
    ~/Library/Application Support/Cursor/user/keybindings.json: cursor/keybindings.json
    ~/.local/state/crossnote/style.less: cursor/markdown-styles/style.less

- shell:
    -
      - "bash brew.sh"
      - "Installing Homebrew packages and applications"
    -
      - "tempfile=$(mktemp) \
        && curl -o $tempfile https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo \
        && tic -x -o ~/.terminfo $tempfile \
        && rm $tempfile"
      - "Installing WezTerm terminfo"
    -
      - "ln -sf $(brew --prefix)/share/git-core/contrib/diff-highlight/diff-highlight /usr/local/bin/diff-highlight"
      - "Installing improved diff highlighting"
    -
      - "git submodule update --init --recursive --remote"
      - "Installing/updating submodules"
    -
      - "mkdir ~/.vim/undodir"
      - "Checking folder structure exists"
    -
      - "mkdir -p ~/.local/state/crossnote"
      - "Creating markdown stylesheet directory"
    -
       - "bash cursor/manage-extensions.sh install"
       - "Installing Cursor extensions"

