#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

# Define bar parameters as an array
BAR_PARAMS=(
  height=37
  color=$BAR_COLOR
  shadow=$SHADOW
  position=top
  sticky=on
  padding_right=18
  padding_left=18
  blur_radius=20
  corner_radius=9
  y_offset=10
  margin=20
  blur_radius=20
  border_color=$BAR_BORDER_COLOR
  border_width=1
)

# Define default parameters as an array
DEFAULT_PARAMS=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  background.padding_right=$PADDINGS
  background.padding_left=$PADDINGS
  popup.background.border_width=2
  popup.background.corner_radius=11
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.background.shadow.drawing=$SHADOW
)

# Setting up the general bar appearance and default values
sketchybar --bar "${BAR_PARAMS[@]}" \
           --default "${DEFAULT_PARAMS[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/time.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
