###
# Configures the starship schema
###
"$schema" = 'https://starship.rs/config-schema.json'


add_newline = true

#
# Multi line
#


# format = """
# [╭╴](bright-black)\
# $directory\
# $git_branch\
# ${custom.git_status_dirty}\
# ${custom.git_status_clean}\
# $git_state\
# $fill\
# $cmd_duration\
# $git_status\
# $python\
# $go\
# $node\
# $time\
# $line_break\
# [╰─]()\
# $character"""

# format = """
# [╭╴](bright-black)\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $cmd_duration\
# $python\
# $go\
# $node\
# $time\
# $line_break\
# [╰─](bright-black)\
# $character"""

# format = """
#  \
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $cmd_duration\
# $python\
# $go\
# $node\
# $time\
# $line_break\
# $character"""

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$go\
$node\
$java\
$time\
$line_break\
$character"""


#
# Single line
#

# format = """
# $directory\
# $git_branch\
# ${custom.git_status_dirty}\
# ${custom.git_status_clean}\
# $git_state\
# $character"""

# right_format = """
# $cmd_duration\
# $git_status\
# $python\
# $go\
# $node\
# $time"""

continuation_prompt = "[❯ ](bright-black)"

command_timeout = 1000

# [fill]
# style  = 'bright-black'
# symbol = '─'

[directory]
style = "#f2777a"
truncation_length = 1
# truncation_length = 2
truncate_to_repo = true
# truncation_symbol = "⋯/"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
# success_symbol = "[❯](red)[❯](yellow)[❯](green)"
# error_symbol = "[❯](red)[❯](red)[❯](red)"
# vimcmd_symbol = "[❮](red)[❮](yellow)[❮](green)"

[git_branch]
format = "on [$branch]($style) "
style = "yellow"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
ahead = "[⇡](yellow)${count} "
behind = "[⇣](yellow)${count} "
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](yellow) "
conflicted = "​"
untracked = "[](white) "
modified = "[](#purple) "
staged = "[](green) "
renamed = "[➜](yellow) "
deleted = "[](red) "
stashed = "[≡](cyan) "


[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "!"
style = "red"
format="[$symbol]($style) "
shell = ["sh"]

[custom.git_status_clean]
when = 'git rev-parse --is-inside-work-tree 2>/dev/null && test -z "$(git status --porcelain 2>/dev/null)"'
symbol = " "
shell = ["sh"]

[git_state]
format = '[⚡ $state( $progress_current/$progress_total)]($style) '
style = "green"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-black"

[golang]
format = "go "

[nodejs]
symbol = "node "

[java]
symbol = "java "
style = "#f99157"

[python]
symbol = "py "
